"""
Smart Lighting Control System
=============================

Platform:
    Raspberry Pi + Raspberry Pi OS

Hardware:
    - Raspberry Pi
    - ADS1115 ADC
    - LDR light sensor
    - PCA9685 PWM driver
    - LED

Software:
    - Python 3
    - Flask
    - Adafruit Blinka
    - Adafruit ADS1x15
    - Adafruit PCA9685

Description:
    This program measures ambient light using an LDR connected
    to an ADS1115 ADC and controls LED brightness through a
    PCA9685 PWM driver.

    The system has two operating modes:

    1. Automatic Mode:
       LED brightness is controlled automatically using a PID
       controller to reach the desired ambient light level.

    2. Manual Mode:
       The user can manually set the LED brightness through
       the web interface.

    A Flask web server provides the user interface for
    monitoring and controlling the lighting system.
"""


# ============================================================
# IMPORT LIBRARIES
# ============================================================

from flask import Flask, render_template_string, request, jsonify
import time
import threading

# Raspberry Pi I2C interface
import board
import busio

# ADS1115 ADC library
import adafruit_ads1x15.ads1115 as ADS
from adafruit_ads1x15.analog_in import AnalogIn

# PCA9685 PWM driver library
from adafruit_pca9685 import PCA9685


# ============================================================
# FLASK APPLICATION
# ============================================================

app = Flask(__name__)


# ============================================================
# I2C CONFIGURATION
# ============================================================

# Initialize the I2C bus of the Raspberry Pi.
# The board.SCL and board.SDA pins are automatically mapped
# to the Raspberry Pi hardware I2C pins.
i2c = busio.I2C(board.SCL, board.SDA)


# ============================================================
# ADS1115 CONFIGURATION
# ============================================================

# Initialize the ADS1115 analog-to-digital converter.
ads = ADS.ADS1115(i2c)

# Connect the LDR sensor to ADS1115 channel P0.
ldr = AnalogIn(ads, ADS.P0)


# ============================================================
# PCA9685 CONFIGURATION
# ============================================================

# Initialize the PCA9685 PWM driver.
pca = PCA9685(i2c)

# Set PWM frequency to 1000 Hz.
pca.frequency = 1000

# LED is connected to PCA9685 channel 0.
LED_CHANNEL = 0


# ============================================================
# SYSTEM VARIABLES
# ============================================================

# True  -> Automatic mode
# False -> Manual mode
auto_mode = True

# True  -> LED enabled
# False -> LED disabled
led_enabled = True

# LED brightness selected by the user in manual mode.
manual_brightness = 50

# Desired ambient light level in automatic mode.
target_light = 50

# Current measured ambient light level.
current_light = 0

# Current LED brightness.
current_brightness = 0


# ============================================================
# PID CONTROLLER PARAMETERS
# ============================================================

# Proportional gain
Kp = 1.2

# Integral gain
Ki = 0.05

# Derivative gain
Kd = 0.2


# Previous error used by the derivative term.
previous_error = 0

# Accumulated error used by the integral term.
integral = 0

# Time of the previous PID calculation.
previous_time = time.time()


# Lock prevents simultaneous access to shared variables
# from the control thread and Flask web requests.
lock = threading.Lock()


# ============================================================
# UTILITY FUNCTION
# ============================================================

def clamp(value, minimum, maximum):
    """
    Restrict a value to a specified range.

    Example:
        clamp(120, 0, 100) returns 100
        clamp(-10, 0, 100) returns 0
    """

    if value < minimum:
        return minimum

    if value > maximum:
        return maximum

    return value


# ============================================================
# LIGHT SENSOR FUNCTION
# ============================================================

def read_light():
    """
    Read the voltage generated by the LDR and convert it
    to an approximate light level between 0 and 100%.

    The conversion assumes that the sensor output is
    approximately proportional to the 0-3.3 V range.
    """

    # Read the voltage measured by ADS1115.
    voltage = ldr.voltage

    # Convert voltage to percentage.
    light = (voltage / 3.3) * 100

    # Keep the result between 0 and 100%.
    light = clamp(light, 0, 100)

    return light


# ============================================================
# LED BRIGHTNESS CONTROL
# ============================================================

def set_led_brightness(brightness):
    """
    Set LED brightness using the PCA9685 PWM driver.

    Parameters:
        brightness:
            LED brightness percentage from 0 to 100.
    """

    global current_brightness

    # Limit brightness to the valid range.
    brightness = clamp(brightness, 0, 100)

    # If the LED is disabled, force brightness to zero.
    if not led_enabled:
        brightness = 0

    # Convert percentage (0-100) to PCA9685
    # 16-bit duty cycle (0-65535).
    pwm_value = int((brightness / 100) * 65535)

    # Apply PWM value to the selected PCA9685 channel.
    pca.channels[LED_CHANNEL].duty_cycle = pwm_value

    # Store the current brightness.
    current_brightness = brightness


# ============================================================
# PID CONTROLLER
# ============================================================

def pid_controller():
    """
    Calculate the required LED brightness using PID control.

    The controller attempts to minimize the difference between
    the target light level and the measured ambient light.
    """

    global previous_error
    global integral
    global previous_time

    # Get current time.
    current_time = time.time()

    # Calculate elapsed time.
    dt = current_time - previous_time

    # Prevent division by zero.
    if dt <= 0:
        dt = 0.01

    # Calculate the error between target and measured light.
    error = target_light - current_light

    # Integral term.
    integral = integral + (error * dt)

    # Limit integral accumulation.
    integral = clamp(integral, -1000, 1000)

    # Derivative term.
    derivative = (error - previous_error) / dt

    # Calculate PID output.
    output = (
        (Kp * error)
        +
        (Ki * integral)
        +
        (Kd * derivative)
    )

    # Adjust the current LED brightness.
    new_brightness = current_brightness + output

    # Keep brightness within the valid range.
    new_brightness = clamp(new_brightness, 0, 100)

    # Apply the new brightness.
    set_led_brightness(new_brightness)

    # Save values for the next PID iteration.
    previous_error = error
    previous_time = current_time


# ============================================================
# MAIN CONTROL LOOP
# ============================================================

def control_loop():
    """
    Continuously measure ambient light and control the LED.

    This function runs in a separate background thread so that
    the Flask web server can continue responding to requests.
    """

    global current_light

    while True:

        # Lock shared variables while they are being updated.
        with lock:

            # Read current ambient light.
            current_light = read_light()

            if auto_mode:

                # Automatic PID control.
                pid_controller()

            else:

                # Manual control.
                if led_enabled:

                    set_led_brightness(
                        manual_brightness
                    )

                else:

                    set_led_brightness(0)

        # Wait 100 ms before the next control cycle.
        time.sleep(0.1)


# ============================================================
# WEB INTERFACE
# ============================================================

HTML_PAGE = """

<!DOCTYPE html>

<html lang="fa">

<head>

<meta charset="UTF-8">

<meta name="viewport"
      content="width=device-width, initial-scale=1.0">

<title>سیستم کنترل روشنایی</title>

<style>

body {

    font-family: Arial, sans-serif;

    direction: rtl;

    text-align: center;

    background: #f2f2f2;

    margin: 0;

    padding: 20px;

}

.container {

    max-width: 600px;

    margin: auto;

    background: white;

    padding: 25px;

    border-radius: 15px;

    box-shadow: 0 0 15px rgba(0,0,0,0.1);

}

h1 {

    margin-bottom: 30px;

}

.card {

    background: #f7f7f7;

    padding: 20px;

    margin: 15px 0;

    border-radius: 10px;

}

button {

    padding: 12px 25px;

    margin: 5px;

    border: none;

    border-radius: 8px;

    cursor: pointer;

    font-size: 16px;

}

input {

    padding: 10px;

    font-size: 16px;

    width: 100px;

}

</style>

</head>

<body>

<div class="container">

<h1>
سیستم کنترل هوشمند روشنایی
</h1>


<div class="card">

<h2>
وضعیت سیستم
</h2>

<p>
حالت فعلی:
<span id="mode">
در حال دریافت...
</span>
</p>

<p>
نور محیط:
<span id="light">
0
</span>
%
</p>

<p>
شدت LED:
<span id="brightness">
0
</span>
%
</p>

</div>


<div class="card">

<h2>
انتخاب حالت
</h2>

<button onclick="setMode('auto')">
حالت خودکار
</button>

<button onclick="setMode('manual')">
حالت دستی
</button>

</div>


<div class="card">

<h2>
کنترل LED
</h2>

<button onclick="setLED(true)">
روشن
</button>

<button onclick="setLED(false)">
خاموش
</button>

</div>


<div class="card">

<h2>
کنترل دستی شدت LED
</h2>

<input
    id="brightnessInput"
    type="number"
    min="0"
    max="100"
    value="50"
>

<button onclick="setBrightness()">
اعمال
</button>

</div>


<div class="card">

<h2>
تنظیم نور مطلوب
</h2>

<input
    id="targetInput"
    type="number"
    min="0"
    max="100"
    value="50"
>

<button onclick="setTarget()">
اعمال
</button>

</div>

</div>


<script>

function updateStatus() {

    fetch('/status')

    .then(response => response.json())

    .then(data => {

        document.getElementById('mode').innerText =
            data.mode;

        document.getElementById('light').innerText =
            data.light.toFixed(1);

        document.getElementById('brightness').innerText =
            data.brightness.toFixed(1);

    });

}


function setMode(mode) {

    fetch('/mode', {

        method: 'POST',

        headers: {

            'Content-Type':
            'application/json'

        },

        body: JSON.stringify({

            mode: mode

        })

    });

}


function setLED(state) {

    fetch('/led', {

        method: 'POST',

        headers: {

            'Content-Type':
            'application/json'

        },

        body: JSON.stringify({

            enabled: state

        })

    });

}


function setBrightness() {

    let value =
        document.getElementById(
            'brightnessInput'
        ).value;

    fetch('/brightness', {

        method: 'POST',

        headers: {

            'Content-Type':
            'application/json'

        },

        body: JSON.stringify({

            brightness: Number(value)

        })

    });

}


function setTarget() {

    let value =
        document.getElementById(
            'targetInput'
        ).value;

    fetch('/target', {

        method: 'POST',

        headers: {

            'Content-Type':
            'application/json'

        },

        body: JSON.stringify({

            target: Number(value)

        })

    });

}


/* Update system status every 500 ms. */
setInterval(updateStatus, 500);

updateStatus();

</script>

</body>

</html>

"""


# ============================================================
# FLASK ROUTES
# ============================================================

@app.route('/')
def index():
    """
    Display the main web interface.
    """

    return render_template_string(HTML_PAGE)


@app.route('/status')
def status():
    """
    Return the current system status as JSON.
    """

    with lock:

        return jsonify({

            'mode':
                'Automatic' if auto_mode
                else 'Manual',

            'light':
                current_light,

            'brightness':
                current_brightness,

            'target':
                target_light,

            'led':
                led_enabled

        })


@app.route('/mode', methods=['POST'])
def change_mode():
    """
    Switch between automatic and manual modes.
    """

    global auto_mode
    global integral
    global previous_error

    data = request.get_json()

    mode = data.get('mode')

    with lock:

        if mode == 'auto':

            auto_mode = True

            # Reset PID terms when automatic mode starts.
            integral = 0
            previous_error = 0

        elif mode == 'manual':

            auto_mode = False

            # Apply manual brightness immediately.
            set_led_brightness(
                manual_brightness
            )

    return jsonify({

        'success': True

    })


@app.route('/led', methods=['POST'])
def control_led():
    """
    Enable or disable the LED.
    """

    global led_enabled

    data = request.get_json()

    state = data.get('enabled')

    with lock:

        led_enabled = bool(state)

        if not led_enabled:

            # Turn the LED completely off.
            set_led_brightness(0)

        else:

            # Restore manual brightness if manual mode is active.
            if not auto_mode:

                set_led_brightness(
                    manual_brightness
                )

    return jsonify({

        'success': True

    })


@app.route('/brightness', methods=['POST'])
def change_brightness():
    """
    Change the LED brightness used in manual mode.
    """

    global manual_brightness

    data = request.get_json()

    value = data.get('brightness')

    value = float(value)

    # Limit brightness to 0-100%.
    value = clamp(value, 0, 100)

    manual_brightness = value

    with lock:

        # Apply the new brightness immediately in manual mode.
        if not auto_mode:

            set_led_brightness(
                manual_brightness
            )

    return jsonify({

        'success': True

    })


@app.route('/target', methods=['POST'])
def change_target():
    """
    Change the desired ambient light level for automatic mode.
    """

    global target_light

    data = request.get_json()

    value = data.get('target')

    value = float(value)

    # Limit target light level to 0-100%.
    target_light = clamp(value, 0, 100)

    return jsonify({

        'success': True,

        'target':
            target_light

    })


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == '__main__':

    # Start the lighting control loop in a background thread.
    control_thread = threading.Thread(
        target=control_loop,
        daemon=True
    )

    control_thread.start()

    # Start the Flask web server.
    #
    # host='0.0.0.0' allows other devices on the same network
    # to access the Raspberry Pi web interface.
    #
    # The web interface can be accessed using:
    #
    # http://<RASPBERRY_PI_IP>:5000
    #
    app.run(
        host='0.0.0.0',
        port=5000,
        debug=False
    )